bases:
  - ../../base

namespace: production

labels:
  - pairs:
      env: production
    includeSelectors: false
    includeTemplates: false

images:
  - name: rechlinks/liszto-node
    newName: rechlinks/liszto-node
    newTag: 0.0.3

replicas:
  - name: node-deployment
    count: 2

