bases:
  - ../../base

namespace: production

commonAnnotations:
  linkerd.io/inject: enabled  

images:
  - name: rechlinks/liszto-node
    newName: rechlinks/liszto-node
    newTag: 0.0.7

replicas:
  - name: node-deployment
    count: 2

