apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJyZWNobGlua3MiLCJwYXNzd29yZCI6Ik5ldmVyRm9yZ2V0IiwiZW1haWwiOiJyZWNobGlua3NAcmVjaGxpbmtzLmNvbSIsImF1dGgiOiJjbVZqYUd4cGJtdHpPazVsZG1WeVJtOXlaMlYwIn19fQ==
kind: Secret
metadata:
  name: regcred
  namespace: ingress-nginx
type: kubernetes.io/dockerconfigjson
