apiVersion: v1
kind: Service
metadata:
  name: icecast-service
  namespace: development
spec:
  type: ClusterIP
  selector:
    component: icecast-deployment
  ports:
    - port: 8000
      targetPort: 8000
