apiVersion: apps/v1
kind: Deployment
metadata:
  name: icecast-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      component: icecast-deployment
  template:
    metadata:
      labels:
        component: icecast-deployment
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: icecast
          image: rechlinks/icecast-relay
          imagePullPolicy: Always
          ports:
           - containerPort: 8000
          startupProbe:
            httpGet:
              path: /
              port: 8000
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 2
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 6
            successThreshold: 1
