apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  labels:
    app: ingress-nginx
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override node-service.production.svc.cluster.local:5000;
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;
spec:
  ingressClassName: nginx
  rules:
    - host: linkerd.rechlinks.com
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: node-service
              port:
                number: 5000
