resources:
  - dockerhub-secret.yaml
  - nfs-pv.yaml
  - nfs-pvc.yaml
  - redis-cm.yaml
  - redis.yaml
  - kafka.yaml
  - icecast-service.yaml
  - icecast-deployment.yaml
  - lisztoapp-configmap.yaml
  - node-service.yaml
  - node-deployment.yaml
  - node-hpa.yaml
