apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  namespace: production
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: nfs
  resources:
    requests:
      storage: 500Gi
