apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-deployment
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-deployment
  template:
    metadata:
      labels:
        app: node-deployment
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: node-deployment
          image: rechlinks/liszto-node:0.0.3
          imagePullPolicy: Always
          ports:
           - containerPort: 5000
          volumeMounts:
            - name: nfs
              mountPath: /home/liszto/LISZTO-BACKEND/data
            - name: configurationfile
              mountPath: /home/liszto/LISZTO-BACKEND/configurations/config/ipConfiguration.config.js
              subPath: ipConfiguration.config.js
            - name: configurationfile
              mountPath: /home/liszto/LISZTO-BACKEND/configurations/config/liquidsoap.config.liq
              subPath: liquidsoap.config.liq
            - name: configurationfile
              mountPath: /home/liszto/LISZTO-BACKEND/configurations/config/dbConfiguration.config.js
              subPath: dbConfiguration.config.js
          env:  
            - name: USER_ID
              value: "1000"
            - name: GROUP_ID
              value: "1000"
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs
        - name: configurationfile
          configMap:
            name: configmap-ip-liq
