apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-hpa
  namespace: production
  labels:
    app: node-hpa
spec:
  minReplicas: 2
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-deployment
  targetCPUUtilizationPercentage: 80
